version: "2"

run:
  timeout: 5m

linters:
  disable:
    - unused    # Disabled due to restructuring - some runner types may appear unused
    - errcheck  # Too noisy for test files - use go vet instead

  exclusions:
    rules:
      # Exclude specific issues in internal/runners.go
      - path: internal/runners.go
        linters:
          - unused
      # Don't require error checking in test files
      - path: _test\.go
        linters:
          - errcheck
